name: Rust Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  COVERAGE_THRESHOLD: 70

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:latest
      # https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  quality-check:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
      # https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Check Rust formatting
        run: cargo fmt --check

      - name: Check for clippy warnings
        run: cargo clippy --locked --workspace --all-targets --no-deps --all-features -- -D warnings
